gcp_project_id   = "cloud-webapp-dev"
region           = "us-east1"
zone             = "us-east1-b"
gcp_machine_type = "e2-micro"
ssh_username     = "packer"
image_name       = "centos-stream-8-v20240110"