gcp_project_id   = "cloud-webapp-dev"
region           = "us-east1"
zone             = "us-east1-b"
ssh_username     = "packer"
image_name       = "centos-stream-8-v20240110"
image_family     = "custom-image-family"