name: Integration Test

on:
  pull_request:
    branches:
      - main

env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_HOST: ${{ secrets.DB_HOST }}

jobs:
  build:
    name: testcase_job
    runs-on: ubuntu-latest

    steps:
    - name: Checking out Repo
      uses: actions/checkout@v3

    - name: Setup PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"

        sudo systemctl restart postgresql
    
    - name: "Creating env file"
      run: |
        touch .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_USER=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo "cat .env"
        cat .env
        echo "ls -a ."
        ls -a .
        echo "ls -a ${{ github.workspace }}"
        ls -a ${{ github.workspace }}

    - name: Setting up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Installing dependencies
      run: npm install

    - name: Runing node tests
      run: npm test