name: Integration Test

on:
  pull_request:
    branches:
      - main

env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_HOST: ${{ secrets.DB_HOST }}

jobs:
  build:
    name: testcase_job
    runs-on: ubuntu-latest

    steps:
    - name: Checking out Repo
      uses: actions/checkout@v3

    # - name: Setup PostgreSQL
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y postgresql postgresql-contrib
    #     sudo systemctl start postgresql
    #     sudo systemctl enable postgresql
    #     sudo sed -i 's/peer/scram-sha-256/' /etc/postgresql/*/main/pg_ident.conf
    #     sudo -u postgres psql -c "ALTER USER ${{ secrets.DB_USERNAME }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"
    #     sudo systemctl restart postgresql

    - name: Setup PostgreSQL
      uses: ikalnytskyi/action-setup-postgres@v5
      with:
          username: postgres
          password: postgres
          database: postgres
          port: 5432
      id: postgres
    
    # - run: pytest -vv tests/
    #   env:
    #       CONNECTION_STR: ${{ steps.postgres.outputs.connection-uri }}
    
    # - run: pytest -vv tests/
    #   env:
    #       CONNECTION_STR: service=${{ steps.postgres.outputs.service-name }}
    
    - name: "Creating env file"
      run: |
        touch .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_USER=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo "cat .env"
        cat .env
        echo "ls -a ."
        ls -a .
        echo "ls -a ${{ github.workspace }}"
        ls -a ${{ github.workspace }}

    - name: Setting up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Installing dependencies
      run: npm install

    - name: Runing node tests
      run: npm test