name: Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: testcase_job
    runs-on: ubuntu-latest

    steps:
    - name: Checking out Repo
      uses: actions/checkout@v3

    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install postgresql postgresql-contrib -y
        sudo systemctl start postgresql
        sudo systemctl enable postgresql

    - name: Configure PostgreSQL
      run: |
        sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"
        sudo sed -i 's/127.0.0.1\/32/0.0.0.0\/0/g' /etc/postgresql/*/main/pg_hba.conf
        sudo systemctl restart postgresql
    
    - name: "Creating env file"
      run: |
        touch .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_USER=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo "cat .env"
        cat .env
        echo "ls -a ."
        ls -a .
        echo "ls -a ${{ github.workspace }}"
        ls -a ${{ github.workspace }}

    - name: Setting up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Installing dependencies
      run: npm install

    - name: Runing node tests
      run: npm test